I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rogue_chat.rpy", line 1981, in script
    $ renpy.pop_call()
  File "game/rogue_chat.rpy", line 1981, in <module>
    $ renpy.pop_call()
Exception: No call on call stack.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rogue_chat.rpy", line 1981, in script
    $ renpy.pop_call()
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/rogue_chat.rpy", line 1981, in <module>
    $ renpy.pop_call()
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/exports.py", line 2817, in pop_call
    renpy.game.context().pop_call()
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/execution.py", line 669, in pop_call
    raise Exception("No call on call stack.")
Exception: No call on call stack.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Rogue-Like Chonky Mod 0.2b
Mon Jun 13 20:11:18 2022
