I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cheats.rpy", line 652, in script call
    call WardrobeEditor (Chr)
  File "game/cheats.rpy", line 141, in script
    menu:
Exception: DynamicImage u'images/Rogue_sprite/Rogue_standing_chest[RogueX.piercings].png': could not find image. (u'images/Rogue_sprite/Rogue_standing_chest_ring.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/cheats.rpy", line 652, in script call
    call WardrobeEditor (Chr)
  File "game/cheats.rpy", line 141, in script
    menu:
  File "renpy/ast.py", line 1688, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "renpy/exports.py", line 1060, in menu
    rv = renpy.store.menu(new_items)
  File "renpy/exports.py", line 1296, in display_menu
    rv = renpy.ui.interact(mouse='menu', type=type, roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3737, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 570, in visit_all
    callback(self)
  File "renpy/display/core.py", line 3737, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/image.py", line 752, in per_interact
    self.find_target()
  File "renpy/display/image.py", line 652, in find_target
    raise Exception(error)
Exception: DynamicImage u'images/Rogue_sprite/Rogue_standing_chest[RogueX.piercings].png': could not find image. (u'images/Rogue_sprite/Rogue_standing_chest_ring.png')

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Rogue-Like 0.997f2
Wed May 25 01:13:40 2022
