I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/caught.rpy", line 1411, in script call
    call world_map
  File "game/locations.rpy", line 128, in script call
    call event_calls
  File "game/utilities.rpy", line 986, in script call
    call expression event_Girls[0].tag + "_BF"
  File "game/menus.rpy", line 1107, in script call
    call after_action
  File "game/actions.rpy", line 425, in script call
    call action_specific_consequences(focused_Girl, primary_action)
  File "game/reactions.rpy", line 716, in script
    $ Girl.action_counter[action] += 1
  File "game/reactions.rpy", line 716, in <module>
    $ Girl.action_counter[action] += 1
KeyError: 0

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/caught.rpy", line 1411, in script call
    call world_map
  File "game/locations.rpy", line 128, in script call
    call event_calls
  File "game/utilities.rpy", line 986, in script call
    call expression event_Girls[0].tag + "_BF"
  File "game/menus.rpy", line 1107, in script call
    call after_action
  File "game/actions.rpy", line 425, in script call
    call action_specific_consequences(focused_Girl, primary_action)
  File "game/reactions.rpy", line 716, in script
    $ Girl.action_counter[action] += 1
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Quique\Downloads\renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/reactions.rpy", line 716, in <module>
    $ Girl.action_counter[action] += 1
KeyError: 0

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Rogue-Like 0.997f2
Thu May 26 12:14:57 2022
